#ifndef VERSIONNUMBERS_H_
#define VERSIONNUMBERS_H_

#define VERSION_NUMBER "0.17.3.579"

enum VERSION_NUMBERS{
    VERSION_MAJOR=0,
    VERSION_MINOR=17,
    VERSION_PATCH=3,
    VERSION_BUILD=579
};

#endif

