#ifndef VERSIONNUMBERS_H_
#define VERSIONNUMBERS_H_

#define VERSION_NUMBER "0.17.9.837"

enum VERSION_NUMBERS{
    VERSION_MAJOR=0,
    VERSION_MINOR=17,
    VERSION_PATCH=9,
    VERSION_BUILD=837
};

#endif

