#ifndef VERSIONNUMBERS_H_
#define VERSIONNUMBERS_H_

#define VERSION_NUMBER "0.17.1.545"

enum VERSION_NUMBERS{
    VERSION_MAJOR=0,
    VERSION_MINOR=17,
    VERSION_PATCH=1,
    VERSION_BUILD=545
};

#endif

