#ifndef VERSIONNUMBER_H_
#define VERSIONNUMBER_H_

#define VERSION_STRING "0.18.1.2172"

enum VERSION_NUMBER{
    VERSION_MAJOR=0,
    VERSION_MINOR=18,
    VERSION_PATCH=1,
    VERSION_BUILD=2172
};

#endif

