#ifndef SNAKECONFIG_H_
#define SNAKECONFIG_H_

enum SNAKE_DIRECTION{
    UP=PUSHBUTTON_DIRECTION_UP,
    DOWN=PUSHBUTTON_DIRECTION_DOWN,
    LEFT=PUSHBUTTON_DIRECTION_LEFT,
    RIGHT=PUSHBUTTON_DIRECTION_RIGHT,
    FORWARD=PUSHBUTTON_DIRECTION_FORWARD,
    BACK=PUSHBUTTON_DIRECTION_BACK,
    INVALID=PUSHBUTTON_DIRECTION_INVALID
};

enum SNAKE_LEVEL{
    LEVEL_MIN=1,
    LEVEL_MAX=16,
    LEVEL_DELAY=8,
    LEVEL_BASE=10,
    LEVEL_DEFAULT=8
};

#endif
