#ifndef SNAKECONFIG_H_
#define SNAKECONFIG_H_

enum SNAKE_DIRECTION{
    UP=PUSHBUTTON_DIRECTION_UP,
    DOWN=PUSHBUTTON_DIRECTION_DOWN,
    LEFT=PUSHBUTTON_DIRECTION_LEFT,
    RIGHT=PUSHBUTTON_DIRECTION_RIGHT,
    FORWARD=PUSHBUTTON_DIRECTION_FORWARD,
    BACK=PUSHBUTTON_DIRECTION_BACK,
    INVALID=PUSHBUTTON_DIRECTION_INVALID
};

enum SNAKE_LEVEL{
    LEVEL_MIN=1,
    LEVEL_MAX=16,
    LEVEL_DELAY=8,
    LEVEL_BASE=10,
    LEVEL_DEFAULT=8
};

enum SNAKE_IAP{
    IAP_SECTOR=1,
    IAP_HSCORE_OFFSET=0,
    IAP_HSCORE_SIZE=32,
    IAP_LEVEL_OFFSET=IAP_HSCORE_OFFSET+IAP_HSCORE_SIZE,
    IAP_LEVEL_SIZE=1
};

enum SNAKE_SCORE{
    SCORE_MAX=1024
};

enum SNAKE_SPLASH_SCREEN_EXIT_CODE{
    SNAKE_SPLASH_SCREEN_EXIT_CODE_CANCELED,
    SNAKE_SPLASH_SCREEN_EXIT_CODE_ENTER_GAME
};

#endif
